# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\EE\GitHub\Psoc\NeoPixel\NeoPixel.cydsn\NeoPixel.cyprj
# Date: Mon, 26 Apr 2021 18:06:41 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for D:\EE\GitHub\Psoc\NeoPixel\NeoPixel.cydsn\TopDesign\TopDesign.cysch
# Project: D:\EE\GitHub\Psoc\NeoPixel\NeoPixel.cydsn\NeoPixel.cyprj
# Date: Mon, 26 Apr 2021 18:06:40 GMT
